<?php 
define('BASE_URLD','http://innoappstech.com/event_program/');
define('ERROR_USER_AND_PASS_REQ','Mobile/Email and Password should Not be Blank!!');
define('ERROR_USER_REQ','Mobile/Email should Not be Blank!!');
define('ERROR_PASS_REQ','Password should Not be Blank!!');
define('ERROR_MOB_REQ','Mobile Number should Not be Blank!!');
define('LOGIN_SUCC_MSG','Login Success !!');
define('ERR_LOGIN','Invalid Username and Password!!');
define('ERROR_USER_REQ','User Name should Not be Blank!!');
define('ERROR_EMAIL_REQ','Email should Not be Blank!!');
define('ERROR_NAME_REQ','Name should Not be Blank!!');
define('ERROR_GENDER_REQ','Gender should Not be Blank!!');
define('ERROR_DOB_REQ','Date of Birth should Not be Blank!!');
define('ERROR_PINCODE_REQ','Pincode should Not be Blank!!');
define('ERROR_CATEGORY_REQ','Category should Not be Blank!!');
define('ERROR_MOBILE_ALREADY_EXISTS','Mobile No already Exists!!');
define('ERROR_EMAIL_ALREADY_EXISTS','Email already Exists!!');
define('ERROR_EMAIL_NOT_EXISTS','Email not Exists!!');
define('ERROR_UID_REQ','User Id should Not be Blank!!');
define('REGISTER_SUCCESS','User Successfully Register');
define('ADD_SUCCESS','Successfully Added');
define('REGISTER_ERROR','Error in Register!!');
define('ERROR_EVENT_ALREADY_EXISTS','Event already register!!');
define('EVENT_ADDED_SUCCESS','Event successfully added!!');
define('ERROR_LOCATION_REQ','Location should Not be Blank!!');
define('ERROR_DATE_REQ','Date should Not be Blank!!');
define('ERROR_DESC_REQ','Description should Not be Blank!!');
define('ERROR_TITLE_REQ','Title should Not be Blank!!');
define('ERROR_PID_REQ','Pub Id should Not be Blank!!');
define('ERROR_REG_REQ','Registry Id should Not be Blank!!');
define('EVENT_ADDED_ERROR','Error in adding event!!');
define('POST_ADDED_ERROR','Error in adding post!!');
define('POST_ADDED_SUCCESS','Post successfully added!!');
define('NO_RECORD_FOUND','No Records Found!!');
define('RECORD_FOUND','Records Found!!');
define('ERROR_AN_REQ','Album Name should Not be Blank!!');
define('ERROR_AD_REQ','Album Description should Not be Blank!!');
define('ERROR_ALBUM_ALREADY_EXISTS','Album Name already Exists!!');
define('ERROR_IMAGE_PATH_REQ','Image Path should Not be Blank!!');
define('ERROR_AID_REQ','Album Id should Not be Blank!!');
define('ERROR_IMAGEID_REQ','Image Id should Not be Blank!!');
define('SENT_OTP','Email Successfully Sent!!');
//user login
define('GET_PUB_LIST_COORDINATES','get_pub_list_by_coordinates');
define('GET_PUB_DETAILS','get_pub_details');	
define('pub_rating_comment','pub_rating_c_l');
define('USER_REGISTER','user_register');
define('USER_LOGIN','user_login');		
define('add_memory_bank','add_memory_bank');
define('add_memory_bank_image','add_memory_bank_image');	
define('get_memory_bank_image','get_memory_bank_image');
define('FORGET_PASSWORD','forgot_password');	
define('CHANGE_PASSWORD','change_password');
define('mb_image_like_comment','mb_image_like_comment');	
define('get_memory_bank_details','get_memory_bank_details');
define('mb_like_comment','mb_like_comment');	
define('login_with_fb','login_with_fb');
define('social_login','social_login');	
define('USER_CHECK_IN','user_check_in');
define('USER_Deal_List','user_deal_list');	
define('user_profile_detail','user_profile_detail');	
define('update_user_profile_detail','update_user_profile_detail');	
?>
